### PR TITLE
Improve dockerfile

### PR DESCRIPTION
**Pull request by glacion**

### CODE REVIEW

**Comment by wantyapps** [comment]
About the "Add package-lock.json" (commit 3e75407) I have it in .gitignore, but will use yours.

**Comment by wantyapps** [comment]
@glacion How are we supposed to change package-lock version every tag release?

**Comment by glacion** [comment]
It's good practice to include package-lock.json

**Comment by wantyapps** [comment]
ok...

**Comment by glacion** [comment]
You aren't supposed to change anything in package-lock

**Comment by wantyapps** [comment]
Accepted!

**Comment by wantyapps** [comment]
Wait so is the version tag in package-lock not going to change?

**Comment by wantyapps** [comment]
What if we make a new tag?

**Pull request merged**
